Fix file scripts/inpath: add 4-space tabs

diff --git a/scripts/inpath b/scripts/inpath
--- a/scripts/inpath
+++ b/scripts/inpath
@@ -8,78 +8,49 @@
 # Временно изменяет переменную окружения IFS (Internal Field Separator)
 # Потом меняет ее обратно.
 
-in_path()
-{
-  cmd=$1	ourpath=$2	result=1
-  olfIFS=$IFS	IFS=":"
+in_path() {
+    cmd=$1
+    ourpath=$2
+    result=1
+    olfIFS=$IFS
+    IFS=":"
 
-  for directory in $ourpath
-  do
-    if [ -x $directory/$cmd ] ; then
-      result=0
-    fi
-  done
+    for directory in $ourpath
+    do
+        if [ -x $directory/$cmd ] ; then
+            result=0
+        fi
+    done
 
-  IFS=$oldIFS
-  return $result
+    IFS=$oldIFS
+    return $result
 }
 
-checkForCmdInPath()
-{
-  var=$1
-  if [ "$var" != "" ] ; then
-    if [ "${var:0:1}" = "/" ] ; then
-      if [ ! -x $var ] ; then
-        return 1
-      fi
-    elif ! in_path $var "$PATH" ; then
-      return 2
+checkForCmdInPath() {
+    var=$1
+    if [ "$var" != "" ] ; then
+        if [ "${var:0:1}" = "/" ] ; then
+            if [ ! -x $var ] ; then
+                return 1
+            fi
+        elif ! in_path $var "$PATH" ; then
+            return 2
+        fi
     fi
-  fi
 }
 
-: <<'EOS'
+# : <<'EOS'
 if [ $# -ne 1 ] ; then
-  echo "Usage: $0 command" >&2
-  exit 1
+    echo "Usage: $0 command" >&2
+    exit 1
 fi
 
 checkForCmdInPath "$1"
 case $? in
-  0 ) echo "$1 found in PATH" ;;
-  1 ) echo "$1 not found or not executable" ;;
-  2 ) echo "$1 not found in PATH"
+    0 ) echo "$1 found in PATH" ;;
+    1 ) echo "$1 not found or not executable" ;;
+    2 ) echo "$1 not found in PATH" ;;
 esac
 
 exit 0
-EOS
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
+# EOS
